### ISSUE TITLE
Create mascot

### ISSUE THREAD

**Issue by eddiejaoude** [codemortals/codemortals.github.io#10]

**Comment by andrew-cunliffe** [comment]
https://99designs.co.uk/launch/character-mascot-design/

### Form Questions

- Enter your email and we'll save your work
- What is your organisation name?  
  *e.g. Acme*
- Describe what your organisation or product does and its target audience  
  *e.g. We sell anvils and other industrial goods to manufacturing companies and hobbyists all over the world.*
- Select your industry
- Describe what you want designed  
  *e.g. Describe your aims and requirements in detail here — the more specific, the better. Tell the designers what is required, but also let them know where they’re free to be creative.*
- Is there anything else you would like to communicate to the designers?
- Do you have any images, sketches or documents that might be helpful?  
  *e.g. Your current logo, photos, illustrations, content, layout ideas etc.*

**Comment by andrew-cunliffe** [comment]
## Our Answers (WIP)

### Enter your email and we'll save your work
team AT codemortals.io

### What is your organisation name?
Code Mortals

### Describe what your organisation or product does and its target audience
Our Business
- Advocating software best practices and open source
- Building a community / network of IT professionals
- Speaking at conferences / events
- Hosting technology workshop and training / evening sessions

Audience
- Anyone currently in or wanting to enter software development and IT careers
- (Future) A members network of IT professionals

### Select your industry
Technology & Education

### Describe what you want designed
- Something that is "geeky", for example; wearing glasses / using technology
- Probably an animal (something cute and "mortal"), some ideas;
  - Owls (Wise)
  - Bees (Community)
  - Hawk (Attention to detail)
- Alternatively could be something more "mythical" like Pegasus

### Is there anything else you would like to communicate to the designers?
- Be creative
- We do not want anything that could be portrayed as favouring certain genders or age groups.

### Do you have any images, sketches or documents that might be helpful?
- No

**Comment by eddiejaoude** [comment]
> Alternatively could be something more "mythical" like Pegasus

Combination of animals, like a flying cheetah (bad example but you get what I mean)

**Comment by andrew-cunliffe** [comment]
![1 (1)](https://user-images.githubusercontent.com/773633/60508921-9d1d2700-9cc3-11e9-932b-1b835c205927.png)
