### ISSUE TITLE
Create Favicon

### ISSUE THREAD

**Issue by ugglr** [codemortals/codemortals.github.io#64]
Change the Angular default favicon to custom for codemortals.

![SharedScreenshot](https://user-images.githubusercontent.com/5120880/61046617-32c95c80-a410-11e9-98f4-df2a96efb106.jpg)

**Comment by eddiejaoude** [comment]
Good spot 👍

**Comment by andrew-cunliffe** [comment]
Oh this was fixed a while ago now.... closing :)
